name: Maven CI

on: [push, pull_request]

jobs:
  compile:
    runs-on: ubuntu-latest
    
    name: Compile
    steps:
      - uses: actions/checkout@master
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Compile with Maven 
        run: mvn -B clean compile --file pom.xml
        
  package:
    runs-on: ubuntu-latest
    
    name: Build
    needs: [compile]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
